### ISSUE TITLE
httpd-config-generator fails during ipa configuration generation

### ISSUE THREAD

**Issue by izapolsk** [ManageIQ/httpd_configmap_generator#25]
When I try to generate ipa configuration using latest docker I get the following error:
```
[root@cfme-smicro-628-b09 cfme-59018-0126]# docker exec $CONFIGMAP_GENERATOR_ID httpd_configmap_generator ipa --host=xz3tto.*** --ipa-server=env-freeipa01.*** --ipa-domain=freeipa01.*** --ipa-realm=freeipa01.*** --ipa-principal=admin --ipa-password=*** -f -d -o /tmp/external-ipa.yaml
Running Command: /usr/bin/hostname
Running Command: /usr/bin/hostname --params xz3tto.***
Running Command: /usr/sbin/ipa-client-install --params -N force_join fixed_primary unattended realm\= FREEIPA01.*** domain\= freeipa01.*** server\= env-freeipa01.*** principal\= admin password\= ***
Configuring IPA HTTP Service
Running Command: /usr/bin/kinit --params admin --stdin-data ***
Command Error: /usr/bin/ipa exit code: 2
stdout:
stderr: ipa: ERROR: The host 'xz3tto.***' does not exist to add a service to.
/opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/awesome_spawn-1.4.1/lib/awesome_spawn.rb:105:in `run!': /usr/bin/ipa exit code: 2 (AwesomeSpawn::CommandResultError)
        from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/httpd_configmap_generator-0.2.1/lib/httpd_configmap_generator/base/command.rb:17:in `command_run!'
        from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/httpd_configmap_generator-0.2.1/lib/httpd_configmap_generator/base/principal.rb:30:in `request'
        from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/httpd_configmap_generator-0.2.1/lib/httpd_configmap_generator/base/principal.rb:19:in `register'
        from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/httpd_configmap_generator-0.2.1/lib/httpd_configmap_generator/ipa.rb:115:in `configure_ipa_http_service'
        from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/httpd_configmap_generator-0.2.1/lib/httpd_configmap_generator/ipa.rb:63:in `configure'
        from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/httpd_configmap_generator-0.2.1/lib/httpd_configmap_generator/base.rb:83:in `run_configure'
        from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/httpd_configmap_generator-0.2.1/bin/httpd_configmap_generator:68:in `run'
        from /opt/rubies/ruby-2.3.1/lib/ruby/gems/2.3.0/gems/httpd_configmap_generator-0.2.1/bin/httpd_configmap_generator:87:in `<top (required)>'
        from /opt/rubies/ruby-2.3.1/bin/httpd_configmap_generator:23:in `load'
        from /opt/rubies/ruby-2.3.1/bin/httpd_configmap_generator:23:in `<main>'
```
When I open shell in docker and run kinit + ipa host-add + ipa service-add manually, next attempt to run httpd_configmap_generator finishes successfully.

**Comment by chessbyte** [comment]
@abellotti @jvlcek Is this still a valid issue that we want to address at some point?

**Comment by jvlcek** [comment]
@chessbyte Yes. I think we should see if this is still reproducible and if it is address it. Since the description describes a workaround, although cumbersome, this is not a high priority issue.

**Comment by dayres** [comment]
I am having the same issue when generating a saml configuration:

`
stderr: 
/usr/share/gems/gems/awesome_spawn-1.5.0/lib/awesome_spawn.rb:108:in `run!': /usr/libexec/mod_auth_mellon/mellon_create_metadata.sh exit code: 127 (AwesomeSpawn::CommandResultError)
        from /usr/share/gems/gems/httpd_configmap_generator-0.3.2/lib/httpd_configmap_generator/base/command.rb:17:in `command_run!'
        from /usr/share/gems/gems/httpd_configmap_generator-0.3.2/lib/httpd_configmap_generator/saml.rb:41:in `block in configure'
        from /usr/share/gems/gems/httpd_configmap_generator-0.3.2/lib/httpd_configmap_generator/saml.rb:40:in `chdir'
        from /usr/share/gems/gems/httpd_configmap_generator-0.3.2/lib/httpd_configmap_generator/saml.rb:40:in `configure'
        from /usr/share/gems/gems/httpd_configmap_generator-0.3.2/lib/httpd_configmap_generator/base.rb:80:in `run_configure'
        from /usr/share/gems/gems/httpd_configmap_generator-0.3.2/bin/httpd_configmap_generator:68:in `run'
        from /usr/share/gems/gems/httpd_configmap_generator-0.3.2/bin/httpd_configmap_generator:87:in `<top (required)>'
        from /usr/bin/httpd_configmap_generator:23:in `load'
        from /usr/bin/httpd_configmap_generator:23:in `<main>'
`
